// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.HelloWorld
{
    public partial class ExchangeRequest
    {
        public string PlayerId;
        public CurrencyAmount From;
        public string ToCurrencyId;

        [Preserve]
        public ExchangeRequest ()
        {
        }
    }
}