// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.HelloWorld
{
    public partial class ExchangeResponse
    {
        public long Credited;
        public long Debited;
        public long FeeApplied;
        public string RateUsed;

        [Preserve]
        public ExchangeResponse ()
        {
        }
    }
}