// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.HelloWorld
{
    public partial class CurrencyAmount
    {
        public string CurrencyId;
        public long Amount;

        [Preserve]
        public CurrencyAmount ()
        {
        }
    }
}