// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class MyModuleBindings
    {
        readonly ICloudCodeService k_Service;
        public MyModuleBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<HelloWorld.ExchangeResponse> ExchangeV2(HelloWorld.ExchangeRequest req)
        {
            return await k_Service.CallModuleEndpointAsync<HelloWorld.ExchangeResponse>(
                "exchange_module",
                "ExchangeV2",
                new Dictionary<string, object>()
                {
                    {"req", req},
                });
        }
    }
}
